### ISSUE TITLE
PsalmPlugin installation error

### ISSUE THREAD

**Issue by khalid-eyez** [Practically/PsalmPluginYii2#14]
i have been trying to install this package using composer as specified in the documentation and here is the error that i get

Could not find a version of package practically/psalm-plugin-yii2 matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

how to i solve that problem ?

**Comment by GeorgeCadwallader** [comment]
We currently do not have a release that satisfies your minimum stability of "stable".

Run this command to install the latest `dev` version:

```bash
composer require --dev practically/psalm-plugin-yii2:1.x-dev
```
